version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cep-game-engine-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cep-game-engine
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cep-game-network

volumes:
  db_data:

networks:
  cep-game-network:
    driver: bridge
